version: "3"

services:
  db:
    image: mongo
    container_name: db_mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo_data.json:/data/mongo_data.json:ro
      - ./script/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro  
    entrypoint: /docker-entrypoint-initdb.d/init-mongo.sh
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MY_DATABASE_DRIVER: "mongo"
      DB_HOST: db
      DB_PORT: 27017
    depends_on:
      - db
    ports:
      - 8081:3000
    restart: always
